"use client";

import { Check, Copy, Download, ExternalLink, Plus, Printer, RefreshCw, Trash2 } from "lucide-react";
import { marked } from "marked";
import { PDFDocument } from "pdf-lib";
import { useMemo, useState } from "react";

const inputClass = "w-full rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] px-4 py-3 text-sm text-[var(--foreground)] outline-none focus:border-[var(--brand)]";
const buttonClass = "button-primary px-4 py-3";

function download(name: string, content: BlobPart, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
}

function Actions({ text, filename = "output.txt" }: { text: string; filename?: string }) {
  const [copied, setCopied] = useState(false);
  return <div className="flex flex-wrap gap-2">
    <button className={buttonClass} onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1200); }}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? "Copied" : "Copy"}</button>
    <button className="button-secondary px-4 py-3" onClick={() => download(filename, text)}><Download size={16}/> Download</button>
  </div>;
}

function JsonTool() {
  const [value, setValue] = useState('{"project":"OpenCorex","openSource":true}');
  const [output, setOutput] = useState(value); const [error, setError] = useState(""); const [indent,setIndent]=useState(2); const [query,setQuery]=useState("");
  const sortObject=(input:unknown):unknown=>Array.isArray(input)?input.map(sortObject):input&&typeof input==="object"?Object.fromEntries(Object.entries(input).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sortObject(v)])):input;
  const run = (mode:"format"|"minify"|"sort"|"query" = "format") => { try { let data:unknown=JSON.parse(value); if(mode==="sort")data=sortObject(data); if(mode==="query")data=query.split(".").filter(Boolean).reduce<unknown>((a,k)=>a&&typeof a==="object"?(a as Record<string,unknown>)[k]:undefined,data); setOutput(JSON.stringify(data,null,mode==="minify"?0:indent)); setError(""); } catch (e) { setError(e instanceof Error ? `${e.message}${e.message.match(/position (\d+)/)?.[1]?` (near character ${e.message.match(/position (\d+)/)?.[1]})`:""}` : "Invalid JSON"); } };
  let stats="";try{const data=JSON.parse(value);const walk=(v:unknown):number=>v&&typeof v==="object"?1+Object.values(v).reduce((n,x)=>n+walk(x),0):1;stats=`${new Blob([value]).size} bytes • ${walk(data)} nodes • valid JSON`}catch{stats="Invalid JSON"}
  return <><div className="grid gap-3 sm:grid-cols-[1fr_8rem]"><input className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Path query, e.g. user.name"/><select className={inputClass} value={indent} onChange={e=>setIndent(+e.target.value)}><option value="2">2 spaces</option><option value="4">4 spaces</option><option value="8">8 spaces</option></select></div><textarea className={`${inputClass} min-h-56 font-mono`} value={value} onChange={e=>setValue(e.target.value)}/><p className="text-xs text-[var(--muted)]">{stats}</p><div className="flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>run()}>Format & validate</button><button className="button-secondary px-4 py-3" onClick={()=>run("minify")}>Minify</button><button className="button-secondary px-4 py-3" onClick={()=>run("sort")}>Deep-sort keys</button><button className="button-secondary px-4 py-3" onClick={()=>run("query")}>Run path query</button></div>{error && <p className="text-sm text-red-400">{error}</p>}<pre className="min-h-32 overflow-auto rounded-xl bg-black/40 p-4 text-sm text-emerald-300">{output}</pre><Actions text={output} filename="data.json"/></>;
}

function PasswordTool() {
  const [length,setLength]=useState(24); const [sets,setSets]=useState({upper:true,lower:true,numbers:true,symbols:true}); const [count,setCount]=useState(5); const [passwords,setPasswords]=useState<string[]>([]);
  const chars=`${sets.upper?"ABCDEFGHJKLMNPQRSTUVWXYZ":""}${sets.lower?"abcdefghijkmnopqrstuvwxyz":""}${sets.numbers?"23456789":""}${sets.symbols?"!@#$%^&*_-+=":""}`;
  const make=()=>{if(!chars)return;setPasswords(Array.from({length:count},()=>{const bytes=crypto.getRandomValues(new Uint32Array(length));return Array.from(bytes,n=>chars[n%chars.length]).join("")}));}; const entropy=chars?Math.floor(length*Math.log2(chars.length)):0;
  return <><div className="grid gap-4 sm:grid-cols-2"><label>Length: {length}<input className="mt-2 w-full" type="range" min="8" max="128" value={length} onChange={e=>setLength(+e.target.value)}/></label><label>Quantity<select className={`${inputClass} mt-2`} value={count} onChange={e=>setCount(+e.target.value)}>{[1,5,10,25].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(sets).map(([k,v])=><label className="data-card flex gap-2 rounded-xl p-3 capitalize" key={k}><input type="checkbox" checked={v} onChange={e=>setSets({...sets,[k]:e.target.checked})}/>{k}</label>)}</div><div className="rounded-xl bg-white/5 p-3 text-sm">Estimated entropy: <b>{entropy} bits</b> · {entropy>=100?"Excellent":entropy>=60?"Strong":"Increase length or character sets"}</div><button className={buttonClass} onClick={make}><RefreshCw size={16}/> Generate secure batch</button><div className="max-h-72 space-y-2 overflow-auto">{passwords.map((p,i)=><button className="block w-full break-all rounded-xl bg-black/40 p-3 text-left font-mono hover:bg-white/10" onClick={()=>navigator.clipboard.writeText(p)} key={i}>{p}</button>)}</div>{passwords.length>0&&<Actions text={passwords.join("\n")} filename="passwords.txt"/>}</>;
}

function TextTool() {
  const [text,setText]=useState(""); const words=text.trim()?text.trim().split(/\s+/).length:0;
  const transform=(kind:string)=>setText(kind==="upper"?text.toUpperCase():kind==="lower"?text.toLowerCase():kind==="dedupe"?[...new Set(text.split("\n"))].join("\n"):kind==="sort"?text.split("\n").sort().join("\n"):text.replace(/\s+/g," ").trim());
  return <><div className="grid grid-cols-3 gap-3">{[[words,"Words"],[text.length,"Characters"],[text.split("\n").length,"Lines"]].map(([v,l])=><div className="data-card rounded-xl p-3 text-center" key={String(l)}><b className="text-xl">{v}</b><div className="text-xs text-[var(--muted)]">{l}</div></div>)}</div><textarea className={`${inputClass} min-h-56`} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text here…"/><div className="flex flex-wrap gap-2">{["upper","lower","clean","dedupe","sort"].map(x=><button className="button-secondary px-3 py-2 capitalize" onClick={()=>transform(x)} key={x}>{x}</button>)}</div><Actions text={text}/></>;
}

function EncoderTool() {
  const [text,setText]=useState(""); const [result,setResult]=useState("");
  const hash=async()=>setResult(Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,"0")).join(""));
  const jwt=()=>{try{const [header,payload]=text.split(".");const decode=(x:string)=>JSON.parse(atob(x.replace(/-/g,"+").replace(/_/g,"/")));setResult(JSON.stringify({header:decode(header),payload:decode(payload),note:"Signature is displayed but not cryptographically verified."},null,2))}catch{setResult("Invalid JWT structure")}};
  return <><textarea className={`${inputClass} min-h-36`} value={text} onChange={e=>setText(e.target.value)} placeholder="Enter text, encoded value, or JWT…"/><div className="flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>setResult(btoa(unescape(encodeURIComponent(text))))}>Base64 encode</button><button className="button-secondary px-3 py-2" onClick={()=>{try{setResult(decodeURIComponent(escape(atob(text))))}catch{setResult("Invalid Base64")}}}>Base64 decode</button><button className="button-secondary px-3 py-2" onClick={()=>setResult(encodeURIComponent(text))}>URL encode</button><button className="button-secondary px-3 py-2" onClick={()=>{try{setResult(decodeURIComponent(text))}catch{setResult("Invalid URL encoding")}}}>URL decode</button><button className="button-secondary px-3 py-2" onClick={hash}>SHA-256</button><button className="button-secondary px-3 py-2" onClick={jwt}>Inspect JWT</button><button className="button-secondary px-3 py-2" onClick={()=>setResult(crypto.randomUUID())}>UUID v4</button></div><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all rounded-xl bg-black/40 p-4">{result}</pre>{result&&<Actions text={result}/>}</>;
}

function ImageTool() {
  const [quality,setQuality]=useState(.8),[maxWidth,setMaxWidth]=useState(1920),[format,setFormat]=useState("image/webp"); const [files,setFiles]=useState<File[]>([]); const [results,setResults]=useState<{name:string,url:string,before:number,after:number,width:number,height:number}[]>([]),[busy,setBusy]=useState(false);
  const process=async()=>{setBusy(true);results.forEach(x=>URL.revokeObjectURL(x.url));const next=[];for(const file of files){const bitmap=await createImageBitmap(file),scale=Math.min(1,maxWidth/bitmap.width),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,format,quality));if(blob)next.push({name:file.name.replace(/\.[^.]+$/,format==="image/webp"?".webp":format==="image/png"?".png":".jpg"),url:URL.createObjectURL(blob),before:file.size,after:blob.size,width:canvas.width,height:canvas.height});bitmap.close()}setResults(next);setBusy(false)};
  return <><input className={inputClass} type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><div className="grid gap-4 sm:grid-cols-3"><label>Quality: {Math.round(quality*100)}%<input className="mt-3 w-full" type="range" min=".2" max="1" step=".05" value={quality} onChange={e=>setQuality(+e.target.value)}/></label><label>Maximum width<input className={`${inputClass} mt-2`} type="number" min="320" max="8000" value={maxWidth} onChange={e=>setMaxWidth(+e.target.value)}/></label><label>Output format<select className={`${inputClass} mt-2`} value={format} onChange={e=>setFormat(e.target.value)}><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label></div><button disabled={!files.length||busy} className={`${buttonClass} disabled:opacity-40`} onClick={process}>{busy?<RefreshCw className="animate-spin" size={16}/>:<ImageDownIcon/>} {busy?"Processing batch…":`Compress ${files.length||""} image${files.length===1?"":"s"}`}</button><div className="grid gap-3 sm:grid-cols-2">{results.map(x=><div className="data-card rounded-xl p-4" key={x.url}><img src={x.url} alt="Compressed preview" className="mb-3 h-40 w-full rounded-lg object-contain"/><b>{x.name}</b><p className="text-xs text-[var(--muted)]">{x.width}×{x.height} · {(x.before/1024).toFixed(0)} KB → {(x.after/1024).toFixed(0)} KB · {Math.max(0,100-x.after/x.before*100).toFixed(0)}% smaller</p><a className="mt-3 inline-flex items-center gap-2 text-sm font-bold" href={x.url} download={x.name}><Download size={15}/> Download</a></div>)}</div></>;
}

function ImageDownIcon(){return <Download size={16}/>}

function MarkdownTool() {
  const [text,setText]=useState("# My document\n\nWrite **clear** Markdown here.\n\n- Fast\n- Private\n- Open source");
  const html=useMemo(()=>marked.parse(text,{breaks:true,gfm:true}) as string,[text]);
  return <><div className="flex flex-wrap gap-2"><button className="button-secondary px-3 py-2" onClick={()=>setText(text+"\n## Heading\n")}>Heading</button><button className="button-secondary px-3 py-2" onClick={()=>setText(text+"\n[link](https://example.com)\n")}>Link</button><button className="button-secondary px-3 py-2" onClick={()=>setText(text+"\n```ts\nconst ready = true;\n```\n")}>Code block</button><span className="ml-auto text-xs text-[var(--muted)]">{text.trim().split(/\s+/).length} words · {text.length} characters</span></div><div className="grid gap-4 lg:grid-cols-2"><textarea className={`${inputClass} min-h-96 font-mono`} value={text} onChange={e=>setText(e.target.value)}/><div className="prose prose-invert min-h-96 overflow-auto rounded-xl border border-[var(--line)] bg-white/5 p-5" dangerouslySetInnerHTML={{__html:html}}/></div><div className="flex flex-wrap gap-2"><Actions text={text} filename="document.md"/><button className="button-secondary px-4 py-3" onClick={()=>download("document.html",`<!doctype html><meta charset=\"utf-8\"><article>${html}</article>`,"text/html")}><Download size={16}/> Export HTML</button></div></>;
}

function ColorTool({ paletteOnly=false }:{paletteOnly?:boolean}) {
  const [color,setColor]=useState("#8d153a"),[background,setBackground]=useState("#ffffff");
  const rgb=(hex:string)=>{const n=parseInt(hex.slice(1),16);return [n>>16,(n>>8)&255,n&255]}; const lum=(h:string)=>{const c=rgb(h).map(v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)});return .2126*c[0]+.7152*c[1]+.0722*c[2]}; const contrast=(Math.max(lum(color),lum(background))+.05)/(Math.min(lum(color),lum(background))+.05); const palette=[-50,-25,0,25,50].map(d=>`#${rgb(color).map(v=>Math.max(0,Math.min(255,v+d)).toString(16).padStart(2,"0")).join("")}`);
  return <><div className="grid gap-4 sm:grid-cols-2"><label>Primary<input className={`${inputClass} mt-2 h-14`} type="color" value={color} onChange={e=>setColor(e.target.value)}/></label>{!paletteOnly&&<label>Background<input className={`${inputClass} mt-2 h-14`} type="color" value={background} onChange={e=>setBackground(e.target.value)}/></label>}</div><div className="grid grid-cols-5 overflow-hidden rounded-xl">{palette.map(c=><button key={c} style={{background:c}} className="h-28 p-2 text-xs" onClick={()=>navigator.clipboard.writeText(c)}><span className="rounded bg-black/60 px-1">{c}</span></button>)}</div>{!paletteOnly&&<div className="rounded-xl p-6 text-center text-xl font-bold" style={{color,background}}>Contrast {contrast.toFixed(2)}:1 — {contrast>=4.5?"AA pass":"AA fail"}</div>}<Actions text={palette.join("\n")} filename="palette.txt"/></>;
}

function NicTool(){const [nic,setNic]=useState("");let result="Enter a 10 or 12 character NIC";const m=nic.toUpperCase().match(/^(?:(\d{2})(\d{3})\d{4}[VX]|(\d{4})(\d{3})\d{5})$/);if(m){const year=+(m[1]?`19${m[1]}`:m[3]),raw=+(m[2]||m[4]),female=raw>500,day=raw-(female?500:0);const date=new Date(year,0,day);result=day>0&&date.getFullYear()===year?`Birth date: ${date.toLocaleDateString("en-GB")}\nGender code: ${female?"Female":"Male"}\nFormat: ${nic.length===10?"Old":"New"}`:"NIC day code is invalid"}return <><input className={inputClass} value={nic} onChange={e=>setNic(e.target.value.trim())} placeholder="Enter NIC number"/><pre className="rounded-xl bg-black/40 p-5 text-lg">{result}</pre><p className="text-xs text-[var(--muted)]">This decoder checks encoded format only. It does not verify identity or government records.</p></>}

function Coordinates(){const [lat,setLat]=useState("6.9271"),[lng,setLng]=useState("79.8612");const dms=(v:number,pos:string,neg:string)=>{const a=Math.abs(v),d=Math.floor(a),m=Math.floor((a-d)*60),s=((a-d-m/60)*3600).toFixed(2);return `${d}° ${m}′ ${s}″ ${v>=0?pos:neg}`};const valid=!isNaN(+lat)&&!isNaN(+lng)&&Math.abs(+lat)<=90&&Math.abs(+lng)<=180;const result=valid?`${dms(+lat,"N","S")}, ${dms(+lng,"E","W")}`:"Invalid coordinates";return <><div className="grid gap-3 sm:grid-cols-2"><input className={inputClass} value={lat} onChange={e=>setLat(e.target.value)} placeholder="Latitude"/><input className={inputClass} value={lng} onChange={e=>setLng(e.target.value)} placeholder="Longitude"/></div><div className="rounded-xl bg-black/40 p-5 font-mono">{result}</div>{valid&&<a className={`${buttonClass} inline-flex`} target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=15/${lat}/${lng}`}><ExternalLink size={16}/> OpenStreetMap</a>}</>}

function Generator({kind}:{kind:"invoice"|"readme"|"notice"}){const [a,setA]=useState(""),[b,setB]=useState(""),[c,setC]=useState("");const output=kind==="invoice"?`INVOICE\n\nFrom: ${a}\nBill to: ${b}\n\nItems / notes:\n${c}\n\nThank you.`:kind==="readme"?`# ${a||"Project name"}\n\n${b||"Project description"}\n\n## Installation\n\n\`\`\`sh\n${c||"npm install"}\n\`\`\`\n\n## License\n\nMIT`: `PUBLIC NOTICE\n\n${a||"Notice title"}\n\n${b||"What happened and what people should do."}\n\nContact / updated: ${c}`;return <><input className={inputClass} value={a} onChange={e=>setA(e.target.value)} placeholder={kind==="invoice"?"Your organization":kind==="readme"?"Project name":"Notice title"}/><input className={inputClass} value={b} onChange={e=>setB(e.target.value)} placeholder={kind==="invoice"?"Customer":kind==="readme"?"Short description":"Clear public message"}/><textarea className={`${inputClass} min-h-28`} value={c} onChange={e=>setC(e.target.value)} placeholder={kind==="invoice"?"Items, prices, total and payment details":kind==="readme"?"Install command":"Contact and update time"}/><pre className="whitespace-pre-wrap rounded-xl bg-white p-6 text-black">{output}</pre><div className="flex gap-2"><Actions text={output} filename={kind==="readme"?"README.md":`${kind}.txt`}/><button className="button-secondary px-4 py-3" onClick={()=>window.print()}><Printer size={16}/> Print</button></div></>}

function InvoiceTool(){const [from,setFrom]=useState(""),[to,setTo]=useState(""),[currency,setCurrency]=useState("LKR"),[tax,setTax]=useState(0),[number,setNumber]=useState("INV-001"),[items,setItems]=useState([{description:"Professional services",quantity:1,rate:0}]);const subtotal=items.reduce((n,x)=>n+x.quantity*x.rate,0),taxAmount=subtotal*tax/100,total=subtotal+taxAmount;const output=`INVOICE ${number}\nDate: ${new Date().toLocaleDateString("en-GB")}\nFrom: ${from}\nBill to: ${to}\n\n${items.map(x=>`${x.description} | ${x.quantity} × ${currency} ${x.rate.toFixed(2)} = ${currency} ${(x.quantity*x.rate).toFixed(2)}`).join("\n")}\n\nSubtotal: ${currency} ${subtotal.toFixed(2)}\nTax (${tax}%): ${currency} ${taxAmount.toFixed(2)}\nTOTAL: ${currency} ${total.toFixed(2)}`;return <><div className="grid gap-3 sm:grid-cols-2"><input className={inputClass} value={from} onChange={e=>setFrom(e.target.value)} placeholder="Business / sender details"/><input className={inputClass} value={to} onChange={e=>setTo(e.target.value)} placeholder="Customer / billing details"/><input className={inputClass} value={number} onChange={e=>setNumber(e.target.value)} placeholder="Invoice number"/><div className="grid grid-cols-2 gap-2"><select className={inputClass} value={currency} onChange={e=>setCurrency(e.target.value)}>{["LKR","USD","EUR","GBP","AUD"].map(x=><option key={x}>{x}</option>)}</select><input className={inputClass} type="number" min="0" value={tax} onChange={e=>setTax(+e.target.value)} placeholder="Tax %"/></div></div><div className="space-y-2">{items.map((item,i)=><div className="grid grid-cols-[1fr_5rem_7rem_auto] gap-2" key={i}><input className={inputClass} value={item.description} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><input className={inputClass} type="number" min="0" value={item.quantity} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,quantity:+e.target.value}:x))}/><input className={inputClass} type="number" min="0" value={item.rate} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,rate:+e.target.value}:x))}/><button onClick={()=>setItems(items.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}</div><button className="button-secondary px-3 py-2" onClick={()=>setItems([...items,{description:"New item",quantity:1,rate:0}])}><Plus size={16}/> Add line item</button><pre className="whitespace-pre-wrap rounded-xl bg-white p-7 text-black">{output}</pre><div className="flex flex-wrap gap-2"><Actions text={output} filename={`${number}.txt`}/><button className="button-secondary px-4 py-3" onClick={()=>window.print()}><Printer size={16}/> Print / save PDF</button></div></>}

function Checklist(){const defaults=["Water and non-perishable food","Medicines and first-aid kit","Torch, radio, and spare batteries","Copies of important documents","Emergency contacts and meeting point"];const [items,setItems]=useState(defaults.map((text,i)=>({id:i,text,done:false})));const [next,setNext]=useState("");return <><div className="space-y-2">{items.map(x=><label className="data-card flex items-center gap-3 rounded-xl p-3" key={x.id}><input type="checkbox" checked={x.done} onChange={()=>setItems(items.map(i=>i.id===x.id?{...i,done:!i.done}:i))}/><span className={x.done?"line-through opacity-50":""}>{x.text}</span><button className="ml-auto" onClick={()=>setItems(items.filter(i=>i.id!==x.id))}><Trash2 size={15}/></button></label>)}</div><div className="flex gap-2"><input className={inputClass} value={next} onChange={e=>setNext(e.target.value)} placeholder="Add an item"/><button className={buttonClass} onClick={()=>{if(next.trim()){setItems([...items,{id:Date.now(),text:next.trim(),done:false}]);setNext("")}}}><Plus size={16}/></button></div><button className="button-secondary px-4 py-3" onClick={()=>window.print()}><Printer size={16}/> Print checklist</button></>}

function PdfTool(){const [files,setFiles]=useState<File[]>([]),[pages,setPages]=useState("1"),[status,setStatus]=useState("");const pdfBlob=async(doc:PDFDocument)=>Uint8Array.from(await doc.save()).buffer;const merge=async()=>{try{setStatus("Processing…");const out=await PDFDocument.create();for(const file of files){const src=await PDFDocument.load(await file.arrayBuffer());const copied=await out.copyPages(src,src.getPageIndices());copied.forEach(p=>out.addPage(p))}download("merged.pdf",await pdfBlob(out),"application/pdf");setStatus(`Merged ${files.length} files into ${out.getPageCount()} pages.`)}catch(e){setStatus(e instanceof Error?e.message:"Unable to process PDF")}};const extract=async()=>{if(!files[0])return;try{const src=await PDFDocument.load(await files[0].arrayBuffer()),out=await PDFDocument.create();const indices=[...new Set(pages.split(",").flatMap(part=>{const [a,b]=part.trim().split("-").map(Number);return b?Array.from({length:b-a+1},(_,i)=>a+i-1):[a-1]}))].filter(i=>i>=0&&i<src.getPageCount());(await out.copyPages(src,indices)).forEach(p=>out.addPage(p));download("extracted-pages.pdf",await pdfBlob(out),"application/pdf");setStatus(`Extracted ${indices.length} pages.`)}catch(e){setStatus(e instanceof Error?e.message:"Unable to extract pages")}};return <><input className={inputClass} type="file" accept="application/pdf" multiple onChange={e=>{setFiles(Array.from(e.target.files||[]));setStatus("")}}/><div className="space-y-2">{files.map((f,i)=><div className="data-card flex justify-between rounded-xl p-3" key={f.name+i}><span>{i+1}. {f.name}</span><span className="text-[var(--muted)]">{(f.size/1048576).toFixed(2)} MB</span></div>)}</div><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input className={inputClass} value={pages} onChange={e=>setPages(e.target.value)} placeholder="Pages: 1,3,5-8"/><button disabled={!files.length} className="button-secondary px-4 py-3 disabled:opacity-40" onClick={extract}>Extract from first PDF</button></div><button disabled={files.length<2} className={`${buttonClass} disabled:opacity-40`} onClick={merge}><Download size={16}/> Merge PDFs</button>{status&&<p className="rounded-xl bg-white/5 p-3 text-sm">{status}</p>}<p className="text-xs text-[var(--muted)]">Encrypted PDFs may require removal of their password first. Files never leave this device.</p></>}

const firstAid=[{t:"Severe bleeding",d:"Call emergency services. Apply firm, direct pressure with a clean cloth. Keep pressure on until help arrives."},{t:"Unresponsive person",d:"Check breathing, call emergency services, and begin CPR if trained. Use an AED when available."},{t:"Burns",d:"Cool under clean, cool running water for 20 minutes. Do not apply ice, creams, or break blisters."},{t:"Choking",d:"Encourage coughing if possible. If they cannot breathe or speak, call emergency services and give trained choking first aid."},{t:"Suspected fracture",d:"Keep the injured area still. Do not straighten it. Control bleeding and seek medical care."}];
function FirstAid(){return <><div className="rounded-xl border border-red-500/40 bg-red-500/10 p-4 text-sm">This is a quick reference, not medical diagnosis or training. Contact local emergency services for serious or uncertain conditions.</div><div className="space-y-3">{firstAid.map(x=><details className="data-card rounded-xl p-4" key={x.t}><summary className="cursor-pointer font-bold">{x.t}</summary><p className="mt-3 text-sm text-[var(--muted)]">{x.d}</p></details>)}</div></>}

export default function ToolWorkbench({slug,title,description}:{slug:string;title:string;description:string}){let body:React.ReactNode;switch(slug){case"json-formatter":body=<JsonTool/>;break;case"image-compressor":body=<ImageTool/>;break;case"password-generator":body=<PasswordTool/>;break;case"markdown-editor":body=<MarkdownTool/>;break;case"pdf-toolkit":body=<PdfTool/>;break;case"developer-encoder":body=<EncoderTool/>;break;case"color-toolkit":body=<ColorTool/>;break;case"palette-generator":body=<ColorTool paletteOnly/>;break;case"text-toolkit":body=<TextTool/>;break;case"invoice-generator":body=<InvoiceTool/>;break;case"readme-generator":body=<Generator kind="readme"/>;break;case"nic-decoder":body=<NicTool/>;break;case"emergency-checklist":body=<Checklist/>;break;case"public-notice":body=<Generator kind="notice"/>;break;case"coordinate-converter":body=<Coordinates/>;break;case"first-aid":body=<FirstAid/>;break;default:body=null}return <div className="space-y-8 pb-12"><section className="panel-strong rounded-[2rem] p-7 sm:p-10"><div className="accent-rule"/><p className="eyebrow mt-5">Advanced OpenCorex workbench</p><h1 className="mt-3 text-3xl font-bold sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-[var(--muted)]">{description} Your data stays in this browser.</p></section><section className="panel-strong mx-auto max-w-5xl space-y-4 rounded-[2rem] p-5 sm:p-8">{body}</section></div>}
